server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: USER-SERVICE
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  queue:
    name: user-aud
  exchange:
    name: user-aud_exchange
  routing:
    key: user-aud_key